### ISSUE TITLE
Build_dataset.py won't work

### ISSUE THREAD

**Issue by ThomasMortell** [ryanpmcintire/nfl_py3#1]
Getting this error when running '$python3 build_dataset.py':

Traceback (most recent call last):
  File "build_dataset.py", line 1, in <module>
    from myScraper import parse_season
  File "/home/thomas/Desktop/nfl_py3-master/myScraper.py", line 3, in <module>
    from user_agent import generate_user_agent
ModuleNotFoundError: No module named 'user_agent'

Any help would be amazing thank you :+1:

**Comment by ryanpmcintire** [comment]
Closing as this is not an issue with the code
