### ISSUE TITLE
Error in Master with Data

### ISSUE THREAD

**Issue by omar319** [ryanpmcintire/nfl_py3#45]
Seem to have the following error on your master, maybe it's not retrieving data properly or something is missing?

```
Traceback (most recent call last):
  File "./nfl_py3/modules/main.py", line 26, in <module>
    add_new_week(previousWeek, 2012, previousWeekYear)
  File "./nfl_py3/modules/build_dataset.py", line 97, in add_new_week
    raise err
  File "./nfl_py3/modules/build_dataset.py", line 94, in add_new_week
    parse(file_descriptor, team, verbose_name, endyear, week)
  File "./nfl_py3/modules/build_dataset.py", line 48, in parse
    for season in parse_season(team, verbose_name, year, week):
  File "./nfl_py3/modules/pfr_scraper.py", line 136, in parse_season
    box_score_rows = parse_boxscore(boxscore_uri, session_object)
  File "./nfl_py3/modules/pfr_scraper.py", line 170, in parse_boxscore
    all_game_info.find(text=lambda text: isinstance(text, Comment)), "html.parser"  # type: ignore
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by ryanpmcintire** [comment]
I've added an issue template. Since this report doesn't have enough information for us to reproduce, request that you re-open the issue using the template.
